### ISSUE TITLE
Any idea why gradio isn't show the fille to play/waveform in the gradio webUI?

### ISSUE THREAD

**Issue by MackNcD** [daswer123/xtts-finetune-webui#1]
I'm getting an error in both those sections. The output file is produced -- that's all well and good, so it's not like I can't play it, its just a bit less convenient for overall organization to have this error.

I tried changing it a little bit but I'm not even sure if I've even found the source of the issue, and I didn't have much success -- here's my attempt:
```

def generate_audio(text, languages, speaker_value_text, speaker_path_text, temperature, length_penalty, repetition_penalty, top_k, top_p, speed, sentence_split):


    ref_speaker_wav = ""

    if speaker_path_text and speaker_value_text == "reference":
        ref_speaker_wav = speaker_path_text
    else:
        ref_speaker_wav = speaker_value_text

    lang_code = reversed_supported_languages[languages]
    options = {
        "temperature": temperature,
        "length_penalty": length_penalty,
        "repetition_penalty": float(repetition_penalty),
        "top_k": top_k,
        "top_p": top_p,
        "speed": speed,
        "sentence_split": sentence_split,
    }

    output_filename = f"output_{speaker_value_text}_{uuid.uuid4()}.wav"
    output_file_path = XTTS.process_tts_to_file(text, lang_code, ref_speaker_wav, options, output_filename)

    # Read the generated waveform
    waveform, _ = gr.processing.read(output_file_path)
    
    return waveform, str(output_file_path)

```

**Comment by daswer123** [comment]
Hi, this question should not be in this project but in [xtts_webui](https://github.com/daswer123/xtts-webui)

Check if you have ffmpeg installed on your system

**Comment by MackNcD** [comment]
> Hi, this question should not be in this project but in [xtts_webui](https://github.com/daswer123/xtts-webui)
> 
> Check if you have ffmpeg installed on your system

Sorry just realized this a bit ago, sent you an edited file, you've probably seen it by now, but I'll give it a looksee.
Is FFMPEG not something pip can take care of?

**Comment by daswer123** [comment]
Unfortunately no, you need to install it yourself, I plan to do an automatic installation, but for now everything needs to be done manually

download ffmpeg https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
and move all the files from the bin folder to the windows folder
