### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8. Error

### ISSUE THREAD

**Issue by anastalaz** [daswer123/xtts-finetune-webui#18]
Has anyone encountered following error at the dataset creation step?

Loading Whisper Model!
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)

**Comment by IbrahimOzmen** [comment]
Model.bin: 100% 3.09G/3.09G [01:13<00:00, 42.1MB/s]
Warning, existing language does not match target language. Updated lang.txt with target language.
Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor

I have this problem. I think its something about cuda version or sth? do you know any idea what this might be?
