### ISSUE TITLE
Torch+Cuda installation issue

### ISSUE THREAD

**Issue by Apok1** [daswer123/xtts-finetune-webui#25]
Hi,

I am having issues with the installation, specifically _"ERROR: Could not find a version that satisfies the requirement torch==2.1.1+cu118 (from versions: 2.2.0+cu118, 2.2.1+cu118, 2.2.2+cu118, 2.3.0+cu118)
ERROR: No matching distribution found for torch==2.1.1+cu118"_

Does it require this specific version and how can I help it find the matching distribution.  Sorry if I'm missing something obvious here and appreciate any assistant.

`Microsoft Windows [Version 10.0.22631.3593]
(c) Microsoft Corporation. All rights reserved.

I:\Ai Voice>git clone https://github.com/daswer123/xtts-finetune-webui
Cloning into 'xtts-finetune-webui'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 97 (delta 27), reused 25 (delta 25), pack-reused 64
Receiving objects: 100% (97/97), 37.07 KiB | 441.00 KiB/s, done.
Resolving deltas: 100% (49/49), done.

I:\Ai Voice>cd xtts-finetune-webui

I:\Ai Voice\xtts-finetune-webui>pip install torch==2.1.1+cu118 torchaudio==2.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
ERROR: Could not find a version that satisfies the requirement torch==2.1.1+cu118 (from versions: 2.2.0+cu118, 2.2.1+cu118, 2.2.2+cu118, 2.3.0+cu118)
ERROR: No matching distribution found for torch==2.1.1+cu118`

**Comment by Apok1** [comment]
Self Solve!

If anyone else has this issue you need to:
Download and installed Python 3.11
Download and installed CUDA Toolkit 11.8

I had more recent versions which was causing the issue

**Comment by Apok1** [comment]
I'm getting a runtime error, this seems to want CUDA 12, but I thought it needed CUDA 11.8?  

Any ideas?

`Existing language matches target language
Loading Whisper Model!
Traceback (most recent call last):
  File "I:\AI Voice\xtts-finetune-webui\xtts_demo.py", line 246, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(audio_path, whisper_model = whisper_model, target_language=language, out_path=out_path, gradio_progress=progress)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\AI Voice\xtts-finetune-webui\utils\formatter.py", line 131, in format_audio_list
    segments = list(segments)
               ^^^^^^^^^^^^^^
  File "I:\AI Voice\xtts-finetune-webui\venv\Lib\site-packages\faster_whisper\transcribe.py", line 1111, in restore_speech_timestamps
    for segment in segments:
  File "I:\AI Voice\xtts-finetune-webui\venv\Lib\site-packages\faster_whisper\transcribe.py", line 508, in generate_segments
    encoder_output = self.encode(segment)
                     ^^^^^^^^^^^^^^^^^^^^
  File "I:\AI Voice\xtts-finetune-webui\venv\Lib\site-packages\faster_whisper\transcribe.py", line 767, in encode
    return self.model.encode(features, to_cpu=to_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded`

**Comment by Apok1** [comment]
I uninstalled the items in the requirements file and let it reinstall then and that seems to have done it!

**Comment by Dids** [comment]
> I uninstalled the items in the requirements file and let it reinstall then and that seems to have done it!

Just to confirm, you didn't install CUDA 12.x at all?
From what I can gather, that specific DLL it's complaining about is only included with 12.x and above, but not with 11.x and below, so I'm not quite sure how simply removing and reinstalling the dependencies fixed it for you.
(and yes, I'm also seeing the same issue and so far haven't been able to find a fix)
