### ISSUE TITLE
Convert to importable or runnable CLI script

### ISSUE THREAD

**Issue by platform-kit** [daswer123/xtts-finetune-webui#4]
Fantastic work on this. Would you have any interest in converting it into a script so it can be imported into another script, or run from CLI? This would make it useful on platforms like Replicate, etc.

I _think_ it should be as simple as extracting the steps from the gradio ui and throwing them all into one big script. I would do it myself, but I can't quite tell what's what.

**Comment by daswer123** [comment]
Thanks, that's a good idea.
I think I'll make it as a separate python file.

**Comment by platform-kit** [comment]
@daswer123 amazing! Can't wait to see it!

**Comment by daswer123** [comment]
Hi, I didn't get around to it, but I found out about the project that did just what you wanted.

https://github.com/Haurrus/xtts-trainer-no-ui-auto

**Comment by platform-kit** [comment]
@daswer123 this is amazing, thank you for pinging me.
