### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by tabulak0** [daswer123/xtts-finetune-webui#52]
copying TTS\vc\modules\freevc\wavlm\config.json -> build\lib.win-amd64-cpython-310\TTS\vc\modules\freevc\wavlm
      running build_ext
      building 'TTS.tts.utils.monotonic_align.core' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for coqui-tts
Failed to build coqui-tts
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (coqui-tts)

D:\02_TTS\xtts-finetune-webui>
I update  Microsoft Visual C++ I don't know what is it

**Comment by lumalisan** [comment]
I had the same problem, just install the Microsoft Visual C++ 14.0 or higher and the Windows 10 SDK, and add the path the installation to the system variables.
