### ISSUE TITLE
KeyError: 'ja'

### ISSUE THREAD

**Issue by potacon** [daswer123/xtts-finetune-webui#68]
A new error occurred. KeyError: 'ja' error occurs. However, I saw in the previous article that the error was resolved by proceeding with an additional fine tune from the producer. Do you know why this error appears?

The data processing was interrupted due an error !! Please check the console to verify the full error message! Error summary: Traceback (most recent call last): File "C:\Users\Admin\Desktop\ai creater\xtts-finetune-webui\xtts_demo.py", line 267, in preprocess_dataset train_meta, eval_meta, audio_total_size = format_audio_list(audio_files, asr_model=asr_model, target_language=language, out_path=out_path, gradio_progress=progress) File "C:\Users\Admin\Desktop\ai creater\xtts-finetune-webui\utils\formatter.py", line 139, in format_audio_list sentence = multilingual_cleaners(sentence, target_language) File "C:\Users\Admin\Desktop\ai creater\xtts-finetune-webui\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 562, in multilingual_cleaners text = expand_numbers_multilingual(text, lang) File "C:\Users\Admin\Desktop\ai creater\xtts-finetune-webui\venv\lib\site-packages\TTS\tts\layers\xtts\tokenizer.py", line 542, in expand_numbers_multilingual text = re.sub(_ordinal_re[lang], lambda m: _expand_ordinal(m, lang), text) KeyError: 'ja'

**Comment by diogocorreiaf** [comment]
Did you manage to get this fixed? 
I'm running into the same error now
